name: captcoin.php

on:
  workflow_dispatch:
    inputs:
      username:
        description: 'CaptchaCoin Username'
        required: true
      password:
        description: 'CaptchaCoin password'
        required: true

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'

      - name: Set executable permission
        run: chmod +x captcoin/captcoin.php

      - name: Run Captcoin.php
        run: php captcoin/captcoin.php
        env:
          USERNAME: ${{ github.event.inputs.username }}
          PASSWORD: 'memeX3213!' #${{ github.event.inputs.password }}
